defmodule Mix.Tasks.Loopctl.RoutesSnapshot do
  @shortdoc "Regenerate mcp-server/test/router-routes.json from LoopctlWeb.Router"

  @moduledoc """
  Writes the router's OWN route table to `mcp-server/test/router-routes.json`.

  ## Why this exists

  `mcp-server/test/route_coverage.test.js` sweeps every `/api/v1` route loopctl serves
  against every route the npm package calls, so a route that loses its MCP tool cannot
  land silently. That sweep needs to know what loopctl serves, and the suite it lives in
  is `node --test` with no BEAM anywhere near it.

  It used to answer that question by PARSING `lib/loopctl_web/router.ex` with regexes, and
  it was wrong about the answer three times in two review rounds: it did not expand
  `resources` (34 routes invisible), it joined a wrapped `resources` declaration but not a
  wrapped verb macro (9 more, one of them live and undeclared), a `#` comment or a blank
  line inside a wrapped declaration dropped the route it interrupted, and a plug mounted
  with no action atom (`get "/openapi", OpenApiSpex.Plug.RenderSpec, []`) was invisible to
  the line matcher entirely. Every one of those was SILENT — the sweep stayed green while
  answering for a surface with a hole in it, which is the one thing a sweep must not do.

  The defect is not any of the four regexes. It is a parser asserting its own
  completeness: nothing compared its answer to the router's. So the parser is gone and
  this task writes the router's own answer instead.

  ## The two halves, and what makes each one red

  This file is generated, not authored, and two guards bind it at both ends:

    * `test/loopctl_web/router_snapshot_test.exs` asserts the checked-in file is byte-
      identical to what `render/0` produces NOW. Edit the router without regenerating and
      `mix test` goes red — in `mix precommit` (the commit hook) and in the CI Test job,
      both of which run on every change to this project.
    * `mcp-server/test/route_coverage.test.js` reads the file as its inventory of what
      loopctl serves. It can no longer disagree with the router, because it no longer has
      an opinion of its own.

  ## Why the file lives under `mcp-server/test/`

  Not tidiness — CI path filtering. `.github/workflows/mcp-server-ci.yml` runs the node
  suite only when `mcp-server/**` changed. With the snapshot there, a router change forces
  a regeneration (the test above), the regeneration touches `mcp-server/**`, and the
  coverage sweep therefore RUNS in CI against the surface that just changed. Parked
  anywhere else — `priv/`, say — a router change would regenerate an artifact the node job
  never re-runs on, and the sweep's verdict on the new surface would be the one from the
  previous PR. `package.json`'s `files` array does not list `test`, so the file ships to
  npm with nothing.

  ## Usage

      mix loopctl.routes_snapshot

  `preferred_envs` pins it to `:test`, which is the env `render/0` is asserted in. The
  route table is env-sensitive in principle (`router.ex` wraps a block in
  `Application.compile_env(:loopctl, :dev_routes, false)`); that block is empty today and
  `:dev_routes` is `true` in both `config/dev.exs` and `config/test.exs`, so nothing
  currently differs — but pinning the env is what keeps the generated bytes and the
  asserted bytes the same question.
  """

  use Mix.Task

  @snapshot_path Path.join(["mcp-server", "test", "router-routes.json"])

  @doc "Where the snapshot is written, relative to the project root."
  def snapshot_path, do: @snapshot_path

  @doc """
  The snapshot document, as the exact bytes that belong in the file.

  ONE ROUTE PER LINE, as a four-element array rather than an object: arrays have an order
  JSON guarantees, so the same route table always renders the same bytes, and a diff reads
  one line per route. `plug_opts` is an atom for a controller action and something else for
  a bare plug mount (`[]` for `OpenApiSpex.Plug.RenderSpec`, a keyword list for SwaggerUI),
  so every value is `inspect`ed rather than assumed to be an action name — assuming one is
  exactly what made `GET /api/v1/openapi` invisible to the parser this replaces.

  EVERY route is written, not just `/api/v1`. The sweep's own scope is narrower, and it
  declares the rest explicitly; a snapshot pre-filtered to `/api/v1` would have made that
  declaration impossible to check.
  """
  def render do
    routes =
      LoopctlWeb.Router
      |> Phoenix.Router.routes()
      |> Enum.map(fn route ->
        [
          route.verb |> Atom.to_string() |> String.upcase(),
          route.path,
          inspect(route.plug),
          inspect(route.plug_opts)
        ]
      end)
      |> Enum.sort_by(fn [verb, path, plug, opts] -> {path, verb, plug, opts} end)

    body = Enum.map_join(routes, ",\n", &("    " <> Jason.encode!(&1)))

    """
    {
      "generated_by": "mix loopctl.routes_snapshot",
      "router": "LoopctlWeb.Router",
      "mix_env": "#{Mix.env()}",
      "columns": ["verb", "path", "plug", "plug_opts"],
      "routes": [
    #{body}
      ]
    }
    """
  end

  @impl Mix.Task
  def run(_args) do
    Mix.Task.run("compile")
    Code.ensure_loaded!(LoopctlWeb.Router)

    contents = render()
    File.write!(@snapshot_path, contents)

    count = contents |> String.split("\n") |> Enum.count(&String.starts_with?(&1, "    ["))
    Mix.shell().info("Wrote #{count} routes to #{@snapshot_path} (MIX_ENV=#{Mix.env()}).")
  end
end
