import Config

# Configure your database
config :loopctl, Loopctl.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "loopctl_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# AdminRepo — same credentials in dev (BYPASSRLS role in production)
config :loopctl, Loopctl.AdminRepo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "loopctl_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 3

# HeavyReadRepo — same credentials/database in dev (BYPASSRLS role in production).
# Small pool in dev. The server-side statement_timeout is applied per-read via SET LOCAL
# (Loopctl.HeavyRead.opts/1), defaulting to 10s in dev since `:heavy_read_statement_timeout_ms`
# is unset here. It is NOT a startup `:parameters` value (pgbouncer rejects that — 08P01,
# US-27.13). See Loopctl.HeavyReadRepo.
config :loopctl, Loopctl.HeavyReadRepo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "loopctl_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 3

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :loopctl, LoopctlWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  # `websocket_options` caps a reassembled multi-frame websocket message (Bandit
  # server-level backstop; see the runtime.exs note).
  http: [ip: {127, 0, 0, 1}, websocket_options: [max_fragmented_message_size: 64_000]],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "jW1/D0/L8Vk/kcM/AFQx9iV+NEkUHGWFtkg+McU35jRwiNokdpvoBuRRmFTH7igt",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:loopctl, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:loopctl, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Enable dev routes for dashboard and mailbox
config :loopctl, dev_routes: true

# WebAuthn relying party — localhost for development
config :loopctl, :webauthn,
  rp_id: "localhost",
  origin: "http://localhost:4000",
  user_verification: "preferred"

# Do not include metadata nor timestamps in development logs
config :logger, :default_handler,
  formatter: {:logger_formatter, %{template: [:level, ": ", :message, "\n"]}}

# Declare the structured metadata keys the app emits (US-27.3 DB-error fields,
# request/tenant context). The dev handler above prints only level + message,
# but this `:default_formatter` declaration is what Credo's
# MissedMetadataKeyInLoggerConfig check reads to know these keys are intended.
config :logger, :default_formatter,
  metadata: [
    :request_id,
    :tenant_id,
    :remote_ip,
    :sqlstate,
    :mapped_code,
    :controller,
    :action,
    :pg_message,
    :duration_ms,
    :repo,
    :source,
    :endpoint
  ]

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
