defmodule LoopctlWeb.Endpoint do
  require Logger
  use Phoenix.Endpoint, otp_app: :loopctl

  # The session is stored in the cookie. It is BOTH signed (tamper-proof) and now
  # ENCRYPTED (`encryption_salt`, a value distinct from `signing_salt`) so the
  # signup-flow payload it carries — the client IP handed to `SignupLive` through
  # the signed session (see the ClientIp note below) — is opaque at rest in the
  # browser, not merely read-only (#461 item 3).
  #
  # ONE-TIME CUTOVER SIDE EFFECT: adding `encryption_salt` converts `_loopctl_key`
  # from signed-only to signed+encrypted, so on the deploy that ships this, every
  # pre-existing browser cookie (signed but not encrypted) can no longer be
  # decrypted by Plug.Session and is silently discarded — a fresh empty session is
  # started. Any in-flight signup relying on the session-carried client IP
  # (SignupLive) and any active browser/LiveView session lose state at cutover.
  # This self-heals within one request and is acceptable for a short signup flow;
  # it is called out here so the transient invalidation is not shipped silently.
  #
  # `http_only: true` (the `:cookie` store's default, made explicit) keeps the
  # cookie off `document.cookie`, and `secure:` marks it HTTPS-only in prod.
  # `secure` is COMPILE-ENV gated (`config :loopctl, :session_secure` — true only in
  # prod, see config/prod.exs): a hardcoded `secure: true` would stop the browser
  # sending the cookie over plain HTTP in dev/test, breaking the LiveView WebSocket
  # session handoff signup relies on. Prod already terminates TLS + `force_ssl`, so
  # HTTP never reaches it.
  @session_options [
    store: :cookie,
    key: "_loopctl_key",
    signing_salt: "M0SC+kIe",
    encryption_salt: "e5HwWdTe",
    same_site: "Lax",
    http_only: true,
    secure: Application.compile_env(:loopctl, :session_secure, false)
  ]

  # The signup rate limiter no longer resolves the client IP from the fragile
  # LiveView connect_info. Instead the HTTP pipeline resolves it (via the
  # `LoopctlWeb.Plugs.ClientIp` plug below, which uses the shared
  # `Loopctl.RemoteIp` resolver) and hands it to `LoopctlWeb.SignupLive` through
  # the SIGNED session (see the `:public_signup` live_session in the router). So
  # the socket only needs the session.
  # `max_frame_size: 64_000` is a transport-layer DoS backstop: Bandit's default
  # websocket frame cap is 8 MB, letting every LiveView handler receive multi-MB
  # payloads (emoji/Zalgo/bignum/8 MB-echo abuse). No LiveView in this app needs
  # a large inbound frame — the biggest legit one is the WebAuthn
  # `attestation_captured` event (attestation_object + client_data_json +
  # credential_id, a few KB); signup/onboarding/wiki carry only tiny events. So
  # 64 KB bounds ALL inbound frames at the transport (over-cap frames are dropped
  # and the connection closed by Bandit). This is defense-in-depth ON TOP OF the
  # per-handler size caps and rate limits.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options], max_frame_size: 64_000],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :loopctl,
    gzip: not code_reloading?,
    only: LoopctlWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Tidewave runtime-introspection MCP (dev-only), mounted above code reloading
  # so its /tidewave/mcp endpoint is available to editor MCP clients in dev.
  if Mix.env() == :dev do
    plug Tidewave
  end

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :loopctl
  end

  # Resolve the real client IP into conn.remote_ip for the WHOLE pipeline
  # (registration rate limiter, logging, session init) via the shared
  # Loopctl.RemoteIp resolver, which resolves `fly-client-ip` and
  # `x-forwarded-for` INDEPENDENTLY — immune to the `remote_ip` two-header
  # wire-order collapse that returns Fly's app IP. Leaves conn.remote_ip as the
  # raw peer when nothing is resolvable (never 0.0.0.0).
  plug LoopctlWeb.Plugs.ClientIp

  plug Plug.RequestId
  # US-27.4: clear tenant_id on every request (before routing).
  # Bandit reuses handler processes across keep-alive requests; if an
  # authenticated request set tenant_id in the process dict and the next
  # public/anonymous request on the same process hits the DB, the slow-query
  # telemetry handler would log that public query with the stale tenant_id.
  # Clearing here ensures every request path (authenticated, public, health)
  # starts with fresh metadata, matching the RequestId pattern.
  plug :clear_tenant_metadata
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  # The byte cap lives in LoopctlWeb.RequestLimits because it is PUBLISHED as well as
  # enforced: the corpus ingest description states it next to its item ceiling (a batch
  # of client-supplied vectors runs out of bytes long before it runs out of items) and
  # LoopctlWeb.ErrorJSON names it in the 413 body. One source, so they cannot drift.
  plug Plug.Parsers,
    parsers: [:urlencoded, :json],
    pass: ["*/*"],
    length: LoopctlWeb.RequestLimits.max_body_bytes(),
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # US-27.3: wraps the router so a DB exception that escapes a controller action
  # uncaught (i.e. NOT via the FallbackController rescue path) still gets the same
  # structured SQLSTATE log (AC-27.3.3) and can never leak raw SQL into the web
  # server crash log (AC-27.3.8). The Plug.Exception backstop
  # (LoopctlWeb.Plugs.DBErrorHandler) still maps the status; this plug adds the
  # logging + sanitization the pure status hook cannot.
  plug LoopctlWeb.Plugs.DBErrorBackstop

  # US-27.4: Clear tenant_id from Logger metadata on every request.
  # Ensures a fresh start regardless of whether the previous request (on a
  # keep-alive Bandit process) was authenticated or not. Prevents stale
  # tenant_id from leaking into slow-query logs of public/anonymous queries.
  @doc false
  def clear_tenant_metadata(conn, _opts) do
    Logger.metadata(tenant_id: nil)
    conn
  end
end
