defmodule LoopctlWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :loopctl

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_loopctl_key",
    signing_salt: "M0SC+kIe",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :loopctl,
    gzip: not code_reloading?,
    only: LoopctlWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :loopctl
  end

  # Resolve client IP behind reverse proxy (nginx) for rate limiting
  plug RemoteIp

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :json],
    pass: ["*/*"],
    length: 2_000_000,
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # US-27.3: wraps the router so a DB exception that escapes a controller action
  # uncaught (i.e. NOT via the FallbackController rescue path) still gets the same
  # structured SQLSTATE log (AC-27.3.3) and can never leak raw SQL into the web
  # server crash log (AC-27.3.8). The Plug.Exception backstop
  # (LoopctlWeb.Plugs.DBErrorHandler) still maps the status; this plug adds the
  # logging + sanitization the pure status hook cannot.
  plug LoopctlWeb.Plugs.DBErrorBackstop
end
