defmodule LoopctlWeb.Endpoint do
  require Logger
  use Phoenix.Endpoint, otp_app: :loopctl

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_loopctl_key",
    signing_salt: "M0SC+kIe",
    same_site: "Lax"
  ]

  # The signup rate limiter no longer resolves the client IP from the fragile
  # LiveView connect_info. Instead the HTTP pipeline resolves it (via the
  # `LoopctlWeb.Plugs.ClientIp` plug below, which uses the shared
  # `Loopctl.RemoteIp` resolver) and hands it to `LoopctlWeb.SignupLive` through
  # the SIGNED session (see the `:public_signup` live_session in the router). So
  # the socket only needs the session.
  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :loopctl,
    gzip: not code_reloading?,
    only: LoopctlWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :loopctl
  end

  # Resolve the real client IP into conn.remote_ip for the WHOLE pipeline
  # (registration rate limiter, logging, session init) via the shared
  # Loopctl.RemoteIp resolver, which resolves `fly-client-ip` and
  # `x-forwarded-for` INDEPENDENTLY — immune to the `remote_ip` two-header
  # wire-order collapse that returns Fly's app IP. Leaves conn.remote_ip as the
  # raw peer when nothing is resolvable (never 0.0.0.0).
  plug LoopctlWeb.Plugs.ClientIp

  plug Plug.RequestId
  # US-27.4: clear tenant_id on every request (before routing).
  # Bandit reuses handler processes across keep-alive requests; if an
  # authenticated request set tenant_id in the process dict and the next
  # public/anonymous request on the same process hits the DB, the slow-query
  # telemetry handler would log that public query with the stale tenant_id.
  # Clearing here ensures every request path (authenticated, public, health)
  # starts with fresh metadata, matching the RequestId pattern.
  plug :clear_tenant_metadata
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :json],
    pass: ["*/*"],
    length: 2_000_000,
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # US-27.3: wraps the router so a DB exception that escapes a controller action
  # uncaught (i.e. NOT via the FallbackController rescue path) still gets the same
  # structured SQLSTATE log (AC-27.3.3) and can never leak raw SQL into the web
  # server crash log (AC-27.3.8). The Plug.Exception backstop
  # (LoopctlWeb.Plugs.DBErrorHandler) still maps the status; this plug adds the
  # logging + sanitization the pure status hook cannot.
  plug LoopctlWeb.Plugs.DBErrorBackstop

  # US-27.4: Clear tenant_id from Logger metadata on every request.
  # Ensures a fresh start regardless of whether the previous request (on a
  # keep-alive Bandit process) was authenticated or not. Prevents stale
  # tenant_id from leaking into slow-query logs of public/anonymous queries.
  @doc false
  def clear_tenant_metadata(conn, _opts) do
    Logger.metadata(tenant_id: nil)
    conn
  end
end
